version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: speckle2_test
    steps:
      - checkout
      - restore_cache:
        key: deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: 
        paths:
          - node_modules
        key: deps-{{ checksum "package.json" }}
      - run: npm run test:server