version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  docker:
    - image: circleci/postgres:latest-ram
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: whoami
      - run: |
        psql -c "\list"
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:server
workflows:
    build-and-test:
      jobs:
        - build-and-test