version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: 'circleci/node:12'
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: speckle2_test
    environment: 
      NODE_ENV: test
      DATABASE_URL: 'postgres://localhost:5432/speckle2_test'

    steps:
      - checkout
      - restore_cache:
          key: 'deps-{{ checksum "package.json" }}'
      - run: 'npm install'
      - save_cache: 
          paths:
            - node_modules
          key: 'deps-{{ checksum "package.json" }}'
      - run: 'node -v'
      - run: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
      - run: 'npm run test:server'